#!/usr/bin/env python3
"""Four real episodes, printed end to end — the record behind the charts.

A chart says a design was right or slow; it cannot show what the agent actually wrote,
what came back, and how the loop closed. This regenerates `docs/walkthroughs.md` from
`results/agent_interaction.json` and the harness's own prompt builder, so the walkthrough
can never drift from the run it describes (same discipline as `dump_conditions.py`).

  python scripts/dump_walkthroughs.py       # writes docs/walkthroughs.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import agent_interaction as A  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "docs/walkthroughs.md"


def episode(eps, **kw):
    for e in eps:
        if all(e.get(k) == v for k, v in kw.items()):
            return e
    raise SystemExit(f"no episode matching {kw}")


def render(e, note: str = "") -> str:
    head = (f"**{e['arm']}** · `{e['question_id']}` · SF{e['sf']} · anchor "
            f"{e['anchor']} — {'correct' if e['score_correct'] else 'WRONG'}"
            f" (f1 {e.get('score_f1')}), {e['round_trips']} round trip"
            f"{'s' if e['round_trips'] != 1 else ''}, {e['wall_ms']:.0f} ms wall")
    lines = [head, ""]
    if note:
        lines += [note, ""]
    for i, c in enumerate(e["calls"], 1):
        lines.append(f"*call {i} → `{c['outcome']}`*, {c['rows']} rows, "
                     f"{c['db_hits']:,} db hits, {c['ms']:.0f} ms"
                     + (f" · violations: `{', '.join(c['violations'])}`"
                        if c.get("violations") else ""))
        lines += ["", "```cypher", c["cypher"].strip(), "```", ""]
    final = (e["final_output"] or "").strip()
    lines += ["*final reply* (tail):", "", "```",
              final[-400:] if final else "(empty — the model returned no content)",
              "```", ""]
    verdict = {k[6:]: v for k, v in e.items() if k.startswith("score_")}
    lines += [f"*verdict*: `{json.dumps(verdict, default=str)}`", ""]
    return "\n".join(lines)


def main() -> None:
    eps = json.loads((REPO / "results/agent_interaction.json").read_text())["episodes"]

    ontology_doc = yaml.safe_load((REPO / "ontology/finbench.ontology.yaml").read_text())
    from seocho.ontology import Ontology
    from seocho.query.hybrid_planner import policy_from_ontology, schema_for_prompt
    ont = Ontology.from_dict(ontology_doc)
    thin = A.labels_only_schema(ont)
    full = schema_for_prompt(ont, policy_from_ontology(ont))

    parts = [
        "# Four real episodes, end to end",
        "",
        "Generated by `scripts/dump_walkthroughs.py` from `results/agent_interaction.json`",
        "— do not edit by hand. The charts say which design was right and which was slow;",
        "these are the runs underneath. Every Cypher block is what the model actually",
        "emitted; every db-hit count is measured.",
        "",
        "The harness owns three parameters the model never writes: `$workspace_id` (tenant",
        "scope), `$limit` (row cap) and `$a` (the account the question names). An anchor a",
        "model inlines as a literal is the defect that turned one question into 38 million",
        "db hits, so the harness supplies it.",
        "",
        "---",
        "",
        "## The prompt, per design",
        "",
        f"Condition 1 (`labels`) carries a {len(A.build_instructions(thin, arm='labels')):,}-"
        f"character prompt; condition 2 (`ontology`) carries "
        f"{len(A.build_instructions(full, arm='ontology')):,}. **The rules text is",
        "identical** — the whole difference is the schema block. Conditions 3 and 4 add no",
        "prompt text at all beyond one rule line for the plan gate: they add enforcement",
        "*outside* the prompt. `docs/conditions.md` carries the full diff.",
        "",
        "<details><summary>Condition 1 — the complete prompt</summary>",
        "",
        "```",
        A.build_instructions(thin, arm="labels"),
        "```",
        "",
        "</details>",
        "",
        "<details><summary>Condition 2 — the complete prompt (same rules, richer schema)"
        "</summary>",
        "",
        "```",
        A.build_instructions(full, arm="ontology"),
        "```",
        "",
        "</details>",
        "",
        "---",
        "",
        "## 1. The same question, four designs — `ext_med_1` at SF10",
        "",
        "*\"Which accounts sent money to account 0 on a transfer whose own `channel_risk`",
        "is 5 or more? Give the five lowest account numbers.\"* The word *own* is the whole",
        "question: `channel_risk` is a property of the TRANSFER relationship, and there is",
        "also a `Channel` node carrying `risk_weight`. Nothing in a list of label names",
        "says which one the question means.",
        "",
    ]

    for arm, note in (
        ("labels", "Reads the risk off the **Channel node** instead of the transfer, so it "
                   "answers a different question — and gets a plausible, wrong list "
                   "(missing account 0, adding account 3). This is the failure the "
                   "ontology arm removes, and it is invisible without the gold."),
        ("ontology", "The schema block names `channel_risk` as a property of TRANSFER, so "
                     "the model binds the relationship. Its first attempt is bad Cypher "
                     "(a variable used outside its scope); the database's own error is "
                     "enough to fix it."),
        ("guardrail", "Same query as condition 2 — the guardrail had nothing to reject "
                      "here. The rulebook costs nothing when the model is already inside "
                      "the contract."),
        ("plan", "Here the guardrail earns its place: the model invented a relationship "
                 "variable `cr` inside a pattern, which is not in the ontology. The "
                 "violation goes back as text and the rewrite is correct."),
    ):
        e = episode(eps, arm=arm, question_id="ext_med_1", sf=10, repeat=0)
        parts += [f"### Condition {A.ARMS.index(arm) + 1} — {arm}", "", render(e, note),
                  "---", ""]

    parts += [
        "## 2. When the gate fires — `int_hard_1` at SF100, condition 4",
        "",
        "The question asks for account pairs whose owners *guarantee one another*. The",
        "model reads that as mutual — and the graph holds 40,001 GUARANTEE edges with not",
        "one reciprocal pair, so the correct query for that reading returns nothing. Eight",
        "round trips: two full executions at 11.2M db hits each, two plan refusals, one",
        "`accept-cost` override that then times out at 60 s, three more attempts, and no",
        "answer. The failure is the *question's* ambiguity, and `int_hard_1b` — the same",
        "question with \"in either direction\" — is kept beside it as the control.",
        "",
        "This is also the honest limit of the plan gate: it refuses queries, and refusing",
        "a query that cannot be made cheap does not produce an answer.",
        "",
    ]
    parts += [render(episode(eps, arm="plan", question_id="int_hard_1", sf=100,
                             repeat=0)), ""]

    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
